base_url = "https://georgealton.com"

title = "George Alton"
description = "My Blog"

author = "George Alton"
theme = "zola-paper"

taxonomies = [
    {name = "tags", rss = true, paginate_by = 5},
]

[markdown]
highlight_code = true
hightlight_theme = "dracula"
