baseURL = "https://georgealton.com/"
languageCode = "en-gb"
title = "George Alton"
theme = "m10c"

[params]
    author = "George Alton"
    description = "My Blog"
    avatar = "me.png"

    [[params.social]]
    name = "github"
    url = "https://github.com/georgealton"

    [[params.social]]
        name = "twitter"
        url = "https://twitter.com/georgealton"