on:
  push:
    branches:
      - main

permissions:
  contents: write

name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install Zola
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ZOLA_VERSION='*'
          gh release download \
            --repo getzola/zola \
            --output - \
            --pattern "zola-${ZOLA_VERSION}-$(uname --machine)-*linux-gnu.tar.gz" \
            | tar xzf - -C /usr/local/bin
      - name: Install Themes
        run: git submodule update --init --recursive
      - name: Build
        run: zola build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
